'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="TSGProductionQATEST")>  _
Partial Public Class TSGDataImporterDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertImportFile(instance As ImportFile)
    End Sub
  Partial Private Sub UpdateImportFile(instance As ImportFile)
    End Sub
  Partial Private Sub DeleteImportFile(instance As ImportFile)
    End Sub
  Partial Private Sub InsertImportFileData(instance As ImportFileData)
    End Sub
  Partial Private Sub UpdateImportFileData(instance As ImportFileData)
    End Sub
  Partial Private Sub DeleteImportFileData(instance As ImportFileData)
    End Sub
  Partial Private Sub InsertImportFileColumn(instance As ImportFileColumn)
    End Sub
  Partial Private Sub UpdateImportFileColumn(instance As ImportFileColumn)
    End Sub
  Partial Private Sub DeleteImportFileColumn(instance As ImportFileColumn)
    End Sub
  Partial Private Sub InsertImportFileTab(instance As ImportFileTab)
    End Sub
  Partial Private Sub UpdateImportFileTab(instance As ImportFileTab)
    End Sub
  Partial Private Sub DeleteImportFileTab(instance As ImportFileTab)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.LESDataImporter.My.MySettings.Default.TSGProductionQATESTConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property ImportFiles() As System.Data.Linq.Table(Of ImportFile)
		Get
			Return Me.GetTable(Of ImportFile)
		End Get
	End Property
	
	Public ReadOnly Property ImportFileDatas() As System.Data.Linq.Table(Of ImportFileData)
		Get
			Return Me.GetTable(Of ImportFileData)
		End Get
	End Property
	
	Public ReadOnly Property ImportFileColumns() As System.Data.Linq.Table(Of ImportFileColumn)
		Get
			Return Me.GetTable(Of ImportFileColumn)
		End Get
	End Property
	
	Public ReadOnly Property ImportFileTabs() As System.Data.Linq.Table(Of ImportFileTab)
		Get
			Return Me.GetTable(Of ImportFileTab)
		End Get
	End Property
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.InsertImportFileDataFromXML")>  _
	Public Function InsertImportFileDataFromXML(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ImportXML", DbType:="VarChar(MAX)")> ByVal importXML As String) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), importXML)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.SaveLoanDataExceptionsSimple")>  _
	Public Function SaveLoanDataExceptionsSimple(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="DealID", DbType:="Int")> ByVal dealID As System.Nullable(Of Integer)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), dealID)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.SaveLoanDataFromImportFileDataOriginal")>  _
	Public Function SaveLoanDataFromImportFileDataOriginal(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="DealID", DbType:="Int")> ByVal dealID As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ImportFileID", DbType:="UniqueIdentifier")> ByVal importFileID As System.Nullable(Of System.Guid), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ImportFileTabID", DbType:="Int")> ByVal importFileTabID As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="LoanNoColumnIndex", DbType:="Int")> ByVal loanNoColumnIndex As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="UserID", DbType:="Int")> ByVal userID As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="DueDateColumnIndex", DbType:="Int")> ByVal dueDateColumnIndex As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="BorrowerNameColumnIndex", DbType:="Int")> ByVal borrowerNameColumnIndex As System.Nullable(Of Integer)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), dealID, importFileID, importFileTabID, loanNoColumnIndex, userID, dueDateColumnIndex, borrowerNameColumnIndex)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.SaveLoanDataFromImportFileDataActual")>  _
	Public Function SaveLoanDataFromImportFileDataActual(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="DealID", DbType:="Int")> ByVal dealID As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ImportFileID", DbType:="UniqueIdentifier")> ByVal importFileID As System.Nullable(Of System.Guid), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="ImportFileTabID", DbType:="Int")> ByVal importFileTabID As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="LoanNoColumnIndex", DbType:="Int")> ByVal loanNoColumnIndex As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="UserID", DbType:="Int")> ByVal userID As System.Nullable(Of Integer)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), dealID, importFileID, importFileTabID, loanNoColumnIndex, userID)
		Return CType(result.ReturnValue,Integer)
	End Function
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.ImportFile")>  _
Partial Public Class ImportFile
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ImportFileID As System.Guid
	
	Private _FileName As String
	
	Private _FilePath As String
	
	Private _CompanyID As System.Nullable(Of Integer)
	
	Private _DealID As System.Nullable(Of Integer)
	
	Private _TemplateID As System.Nullable(Of Integer)
	
	Private _CreatedBy As System.Nullable(Of Integer)
	
	Private _CreatedOn As System.Nullable(Of Date)
	
	Private _IsOriginalData As System.Nullable(Of Boolean)
	
	Private _IsActualData As System.Nullable(Of Boolean)
	
	Private _ExcelToDataSetCompletedOn As System.Nullable(Of Date)
	
	Private _DataTransformCompletedOn As System.Nullable(Of Date)
	
	Private _ValidationCompletedOn As System.Nullable(Of Date)
	
	Private _DatabaseCompletedOn As System.Nullable(Of Date)
	
	Private _DataToLoansCompletedOn As System.Nullable(Of Date)
	
	Private _ImportFileTabs As EntitySet(Of ImportFileTab)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnImportFileIDChanging(value As System.Guid)
    End Sub
    Partial Private Sub OnImportFileIDChanged()
    End Sub
    Partial Private Sub OnFileNameChanging(value As String)
    End Sub
    Partial Private Sub OnFileNameChanged()
    End Sub
    Partial Private Sub OnFilePathChanging(value As String)
    End Sub
    Partial Private Sub OnFilePathChanged()
    End Sub
    Partial Private Sub OnCompanyIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnCompanyIDChanged()
    End Sub
    Partial Private Sub OnDealIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnDealIDChanged()
    End Sub
    Partial Private Sub OnTemplateIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnTemplateIDChanged()
    End Sub
    Partial Private Sub OnCreatedByChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnCreatedByChanged()
    End Sub
    Partial Private Sub OnCreatedOnChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnCreatedOnChanged()
    End Sub
    Partial Private Sub OnIsOriginalDataChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnIsOriginalDataChanged()
    End Sub
    Partial Private Sub OnIsActualDataChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnIsActualDataChanged()
    End Sub
    Partial Private Sub OnExcelToDataSetCompletedOnChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnExcelToDataSetCompletedOnChanged()
    End Sub
    Partial Private Sub OnDataTransformCompletedOnChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDataTransformCompletedOnChanged()
    End Sub
    Partial Private Sub OnValidationCompletedOnChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnValidationCompletedOnChanged()
    End Sub
    Partial Private Sub OnDatabaseCompletedOnChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDatabaseCompletedOnChanged()
    End Sub
    Partial Private Sub OnDataToLoansCompletedOnChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDataToLoansCompletedOnChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._ImportFileTabs = New EntitySet(Of ImportFileTab)(AddressOf Me.attach_ImportFileTabs, AddressOf Me.detach_ImportFileTabs)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ImportFileID", DbType:="UniqueIdentifier NOT NULL", IsPrimaryKey:=true)>  _
	Public Property ImportFileID() As System.Guid
		Get
			Return Me._ImportFileID
		End Get
		Set
			If ((Me._ImportFileID = value)  _
						= false) Then
				Me.OnImportFileIDChanging(value)
				Me.SendPropertyChanging
				Me._ImportFileID = value
				Me.SendPropertyChanged("ImportFileID")
				Me.OnImportFileIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FileName", DbType:="VarChar(50)")>  _
	Public Property FileName() As String
		Get
			Return Me._FileName
		End Get
		Set
			If (String.Equals(Me._FileName, value) = false) Then
				Me.OnFileNameChanging(value)
				Me.SendPropertyChanging
				Me._FileName = value
				Me.SendPropertyChanged("FileName")
				Me.OnFileNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FilePath", DbType:="VarChar(500)")>  _
	Public Property FilePath() As String
		Get
			Return Me._FilePath
		End Get
		Set
			If (String.Equals(Me._FilePath, value) = false) Then
				Me.OnFilePathChanging(value)
				Me.SendPropertyChanging
				Me._FilePath = value
				Me.SendPropertyChanged("FilePath")
				Me.OnFilePathChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CompanyID", DbType:="Int")>  _
	Public Property CompanyID() As System.Nullable(Of Integer)
		Get
			Return Me._CompanyID
		End Get
		Set
			If (Me._CompanyID.Equals(value) = false) Then
				Me.OnCompanyIDChanging(value)
				Me.SendPropertyChanging
				Me._CompanyID = value
				Me.SendPropertyChanged("CompanyID")
				Me.OnCompanyIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DealID", DbType:="Int")>  _
	Public Property DealID() As System.Nullable(Of Integer)
		Get
			Return Me._DealID
		End Get
		Set
			If (Me._DealID.Equals(value) = false) Then
				Me.OnDealIDChanging(value)
				Me.SendPropertyChanging
				Me._DealID = value
				Me.SendPropertyChanged("DealID")
				Me.OnDealIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TemplateID", DbType:="Int")>  _
	Public Property TemplateID() As System.Nullable(Of Integer)
		Get
			Return Me._TemplateID
		End Get
		Set
			If (Me._TemplateID.Equals(value) = false) Then
				Me.OnTemplateIDChanging(value)
				Me.SendPropertyChanging
				Me._TemplateID = value
				Me.SendPropertyChanged("TemplateID")
				Me.OnTemplateIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CreatedBy", DbType:="Int")>  _
	Public Property CreatedBy() As System.Nullable(Of Integer)
		Get
			Return Me._CreatedBy
		End Get
		Set
			If (Me._CreatedBy.Equals(value) = false) Then
				Me.OnCreatedByChanging(value)
				Me.SendPropertyChanging
				Me._CreatedBy = value
				Me.SendPropertyChanged("CreatedBy")
				Me.OnCreatedByChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CreatedOn", DbType:="DateTime")>  _
	Public Property CreatedOn() As System.Nullable(Of Date)
		Get
			Return Me._CreatedOn
		End Get
		Set
			If (Me._CreatedOn.Equals(value) = false) Then
				Me.OnCreatedOnChanging(value)
				Me.SendPropertyChanging
				Me._CreatedOn = value
				Me.SendPropertyChanged("CreatedOn")
				Me.OnCreatedOnChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsOriginalData", DbType:="Bit")>  _
	Public Property IsOriginalData() As System.Nullable(Of Boolean)
		Get
			Return Me._IsOriginalData
		End Get
		Set
			If (Me._IsOriginalData.Equals(value) = false) Then
				Me.OnIsOriginalDataChanging(value)
				Me.SendPropertyChanging
				Me._IsOriginalData = value
				Me.SendPropertyChanged("IsOriginalData")
				Me.OnIsOriginalDataChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsActualData", DbType:="Bit")>  _
	Public Property IsActualData() As System.Nullable(Of Boolean)
		Get
			Return Me._IsActualData
		End Get
		Set
			If (Me._IsActualData.Equals(value) = false) Then
				Me.OnIsActualDataChanging(value)
				Me.SendPropertyChanging
				Me._IsActualData = value
				Me.SendPropertyChanged("IsActualData")
				Me.OnIsActualDataChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ExcelToDataSetCompletedOn", DbType:="DateTime")>  _
	Public Property ExcelToDataSetCompletedOn() As System.Nullable(Of Date)
		Get
			Return Me._ExcelToDataSetCompletedOn
		End Get
		Set
			If (Me._ExcelToDataSetCompletedOn.Equals(value) = false) Then
				Me.OnExcelToDataSetCompletedOnChanging(value)
				Me.SendPropertyChanging
				Me._ExcelToDataSetCompletedOn = value
				Me.SendPropertyChanged("ExcelToDataSetCompletedOn")
				Me.OnExcelToDataSetCompletedOnChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataTransformCompletedOn", DbType:="DateTime")>  _
	Public Property DataTransformCompletedOn() As System.Nullable(Of Date)
		Get
			Return Me._DataTransformCompletedOn
		End Get
		Set
			If (Me._DataTransformCompletedOn.Equals(value) = false) Then
				Me.OnDataTransformCompletedOnChanging(value)
				Me.SendPropertyChanging
				Me._DataTransformCompletedOn = value
				Me.SendPropertyChanged("DataTransformCompletedOn")
				Me.OnDataTransformCompletedOnChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ValidationCompletedOn", DbType:="DateTime")>  _
	Public Property ValidationCompletedOn() As System.Nullable(Of Date)
		Get
			Return Me._ValidationCompletedOn
		End Get
		Set
			If (Me._ValidationCompletedOn.Equals(value) = false) Then
				Me.OnValidationCompletedOnChanging(value)
				Me.SendPropertyChanging
				Me._ValidationCompletedOn = value
				Me.SendPropertyChanged("ValidationCompletedOn")
				Me.OnValidationCompletedOnChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DatabaseCompletedOn", DbType:="DateTime")>  _
	Public Property DatabaseCompletedOn() As System.Nullable(Of Date)
		Get
			Return Me._DatabaseCompletedOn
		End Get
		Set
			If (Me._DatabaseCompletedOn.Equals(value) = false) Then
				Me.OnDatabaseCompletedOnChanging(value)
				Me.SendPropertyChanging
				Me._DatabaseCompletedOn = value
				Me.SendPropertyChanged("DatabaseCompletedOn")
				Me.OnDatabaseCompletedOnChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataToLoansCompletedOn", DbType:="DateTime")>  _
	Public Property DataToLoansCompletedOn() As System.Nullable(Of Date)
		Get
			Return Me._DataToLoansCompletedOn
		End Get
		Set
			If (Me._DataToLoansCompletedOn.Equals(value) = false) Then
				Me.OnDataToLoansCompletedOnChanging(value)
				Me.SendPropertyChanging
				Me._DataToLoansCompletedOn = value
				Me.SendPropertyChanged("DataToLoansCompletedOn")
				Me.OnDataToLoansCompletedOnChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="ImportFile_ImportFileTab", Storage:="_ImportFileTabs", ThisKey:="ImportFileID", OtherKey:="ImportFileID")>  _
	Public Property ImportFileTabs() As EntitySet(Of ImportFileTab)
		Get
			Return Me._ImportFileTabs
		End Get
		Set
			Me._ImportFileTabs.Assign(value)
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_ImportFileTabs(ByVal entity As ImportFileTab)
		Me.SendPropertyChanging
		entity.ImportFile = Me
	End Sub
	
	Private Sub detach_ImportFileTabs(ByVal entity As ImportFileTab)
		Me.SendPropertyChanging
		entity.ImportFile = Nothing
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.ImportFileData")>  _
Partial Public Class ImportFileData
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ImportFileDataID As Integer
	
	Private _ImportFileID As System.Nullable(Of System.Guid)
	
	Private _ImportFileTabID As System.Nullable(Of Integer)
	
	Private _RowKeyName As String
	
	Private _RowIndex As System.Nullable(Of Integer)
	
	Private _ColumnIndex As System.Nullable(Of Integer)
	
	Private _LoanID As System.Nullable(Of Integer)
	
	Private _FieldSetID As System.Nullable(Of Integer)
	
	Private _FieldDataID As System.Nullable(Of Integer)
	
	Private _CellValue As String
	
	Private _CellValueLoanReady As String
	
	Private _IsValid As System.Nullable(Of Boolean)
	
	Private _ImportFileTab As EntityRef(Of ImportFileTab)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnImportFileDataIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnImportFileDataIDChanged()
    End Sub
    Partial Private Sub OnImportFileIDChanging(value As System.Nullable(Of System.Guid))
    End Sub
    Partial Private Sub OnImportFileIDChanged()
    End Sub
    Partial Private Sub OnImportFileTabIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnImportFileTabIDChanged()
    End Sub
    Partial Private Sub OnRowKeyNameChanging(value As String)
    End Sub
    Partial Private Sub OnRowKeyNameChanged()
    End Sub
    Partial Private Sub OnRowIndexChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnRowIndexChanged()
    End Sub
    Partial Private Sub OnColumnIndexChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnColumnIndexChanged()
    End Sub
    Partial Private Sub OnLoanIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnLoanIDChanged()
    End Sub
    Partial Private Sub OnFieldSetIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnFieldSetIDChanged()
    End Sub
    Partial Private Sub OnFieldDataIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnFieldDataIDChanged()
    End Sub
    Partial Private Sub OnCellValueChanging(value As String)
    End Sub
    Partial Private Sub OnCellValueChanged()
    End Sub
    Partial Private Sub OnCellValueLoanReadyChanging(value As String)
    End Sub
    Partial Private Sub OnCellValueLoanReadyChanged()
    End Sub
    Partial Private Sub OnIsValidChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnIsValidChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._ImportFileTab = CType(Nothing, EntityRef(Of ImportFileTab))
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ImportFileDataID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property ImportFileDataID() As Integer
		Get
			Return Me._ImportFileDataID
		End Get
		Set
			If ((Me._ImportFileDataID = value)  _
						= false) Then
				Me.OnImportFileDataIDChanging(value)
				Me.SendPropertyChanging
				Me._ImportFileDataID = value
				Me.SendPropertyChanged("ImportFileDataID")
				Me.OnImportFileDataIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ImportFileID", DbType:="UniqueIdentifier")>  _
	Public Property ImportFileID() As System.Nullable(Of System.Guid)
		Get
			Return Me._ImportFileID
		End Get
		Set
			If (Me._ImportFileID.Equals(value) = false) Then
				Me.OnImportFileIDChanging(value)
				Me.SendPropertyChanging
				Me._ImportFileID = value
				Me.SendPropertyChanged("ImportFileID")
				Me.OnImportFileIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ImportFileTabID", DbType:="Int")>  _
	Public Property ImportFileTabID() As System.Nullable(Of Integer)
		Get
			Return Me._ImportFileTabID
		End Get
		Set
			If (Me._ImportFileTabID.Equals(value) = false) Then
				If Me._ImportFileTab.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnImportFileTabIDChanging(value)
				Me.SendPropertyChanging
				Me._ImportFileTabID = value
				Me.SendPropertyChanged("ImportFileTabID")
				Me.OnImportFileTabIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RowKeyName", DbType:="VarChar(50)")>  _
	Public Property RowKeyName() As String
		Get
			Return Me._RowKeyName
		End Get
		Set
			If (String.Equals(Me._RowKeyName, value) = false) Then
				Me.OnRowKeyNameChanging(value)
				Me.SendPropertyChanging
				Me._RowKeyName = value
				Me.SendPropertyChanged("RowKeyName")
				Me.OnRowKeyNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RowIndex", DbType:="Int")>  _
	Public Property RowIndex() As System.Nullable(Of Integer)
		Get
			Return Me._RowIndex
		End Get
		Set
			If (Me._RowIndex.Equals(value) = false) Then
				Me.OnRowIndexChanging(value)
				Me.SendPropertyChanging
				Me._RowIndex = value
				Me.SendPropertyChanged("RowIndex")
				Me.OnRowIndexChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ColumnIndex", DbType:="Int")>  _
	Public Property ColumnIndex() As System.Nullable(Of Integer)
		Get
			Return Me._ColumnIndex
		End Get
		Set
			If (Me._ColumnIndex.Equals(value) = false) Then
				Me.OnColumnIndexChanging(value)
				Me.SendPropertyChanging
				Me._ColumnIndex = value
				Me.SendPropertyChanged("ColumnIndex")
				Me.OnColumnIndexChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LoanID", DbType:="Int")>  _
	Public Property LoanID() As System.Nullable(Of Integer)
		Get
			Return Me._LoanID
		End Get
		Set
			If (Me._LoanID.Equals(value) = false) Then
				Me.OnLoanIDChanging(value)
				Me.SendPropertyChanging
				Me._LoanID = value
				Me.SendPropertyChanged("LoanID")
				Me.OnLoanIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FieldSetID", DbType:="Int")>  _
	Public Property FieldSetID() As System.Nullable(Of Integer)
		Get
			Return Me._FieldSetID
		End Get
		Set
			If (Me._FieldSetID.Equals(value) = false) Then
				Me.OnFieldSetIDChanging(value)
				Me.SendPropertyChanging
				Me._FieldSetID = value
				Me.SendPropertyChanged("FieldSetID")
				Me.OnFieldSetIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FieldDataID", DbType:="Int")>  _
	Public Property FieldDataID() As System.Nullable(Of Integer)
		Get
			Return Me._FieldDataID
		End Get
		Set
			If (Me._FieldDataID.Equals(value) = false) Then
				Me.OnFieldDataIDChanging(value)
				Me.SendPropertyChanging
				Me._FieldDataID = value
				Me.SendPropertyChanged("FieldDataID")
				Me.OnFieldDataIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CellValue", DbType:="VarChar(4000)")>  _
	Public Property CellValue() As String
		Get
			Return Me._CellValue
		End Get
		Set
			If (String.Equals(Me._CellValue, value) = false) Then
				Me.OnCellValueChanging(value)
				Me.SendPropertyChanging
				Me._CellValue = value
				Me.SendPropertyChanged("CellValue")
				Me.OnCellValueChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CellValueLoanReady", DbType:="VarChar(4000)")>  _
	Public Property CellValueLoanReady() As String
		Get
			Return Me._CellValueLoanReady
		End Get
		Set
			If (String.Equals(Me._CellValueLoanReady, value) = false) Then
				Me.OnCellValueLoanReadyChanging(value)
				Me.SendPropertyChanging
				Me._CellValueLoanReady = value
				Me.SendPropertyChanged("CellValueLoanReady")
				Me.OnCellValueLoanReadyChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsValid", DbType:="Bit")>  _
	Public Property IsValid() As System.Nullable(Of Boolean)
		Get
			Return Me._IsValid
		End Get
		Set
			If (Me._IsValid.Equals(value) = false) Then
				Me.OnIsValidChanging(value)
				Me.SendPropertyChanging
				Me._IsValid = value
				Me.SendPropertyChanged("IsValid")
				Me.OnIsValidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="ImportFileTab_ImportFileData", Storage:="_ImportFileTab", ThisKey:="ImportFileTabID", OtherKey:="ImportFileTabID", IsForeignKey:=true)>  _
	Public Property ImportFileTab() As ImportFileTab
		Get
			Return Me._ImportFileTab.Entity
		End Get
		Set
			Dim previousValue As ImportFileTab = Me._ImportFileTab.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._ImportFileTab.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._ImportFileTab.Entity = Nothing
					previousValue.ImportFileDatas.Remove(Me)
				End If
				Me._ImportFileTab.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.ImportFileDatas.Add(Me)
					Me._ImportFileTabID = value.ImportFileTabID
				Else
					Me._ImportFileTabID = CType(Nothing, Nullable(Of Integer))
				End If
				Me.SendPropertyChanged("ImportFileTab")
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.ImportFileColumn")>  _
Partial Public Class ImportFileColumn
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ImportFileColumnID As Integer
	
	Private _ImportFileID As System.Nullable(Of System.Guid)
	
	Private _ImportFileTabID As System.Nullable(Of Integer)
	
	Private _ColumnName As String
	
	Private _ColumnIndex As System.Nullable(Of Integer)
	
	Private _IsKeyColumn As System.Nullable(Of Boolean)
	
	Private _ImportFileTab As EntityRef(Of ImportFileTab)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnImportFileColumnIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnImportFileColumnIDChanged()
    End Sub
    Partial Private Sub OnImportFileIDChanging(value As System.Nullable(Of System.Guid))
    End Sub
    Partial Private Sub OnImportFileIDChanged()
    End Sub
    Partial Private Sub OnImportFileTabIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnImportFileTabIDChanged()
    End Sub
    Partial Private Sub OnColumnNameChanging(value As String)
    End Sub
    Partial Private Sub OnColumnNameChanged()
    End Sub
    Partial Private Sub OnColumnIndexChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnColumnIndexChanged()
    End Sub
    Partial Private Sub OnIsKeyColumnChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnIsKeyColumnChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._ImportFileTab = CType(Nothing, EntityRef(Of ImportFileTab))
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ImportFileColumnID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property ImportFileColumnID() As Integer
		Get
			Return Me._ImportFileColumnID
		End Get
		Set
			If ((Me._ImportFileColumnID = value)  _
						= false) Then
				Me.OnImportFileColumnIDChanging(value)
				Me.SendPropertyChanging
				Me._ImportFileColumnID = value
				Me.SendPropertyChanged("ImportFileColumnID")
				Me.OnImportFileColumnIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ImportFileID", DbType:="UniqueIdentifier")>  _
	Public Property ImportFileID() As System.Nullable(Of System.Guid)
		Get
			Return Me._ImportFileID
		End Get
		Set
			If (Me._ImportFileID.Equals(value) = false) Then
				Me.OnImportFileIDChanging(value)
				Me.SendPropertyChanging
				Me._ImportFileID = value
				Me.SendPropertyChanged("ImportFileID")
				Me.OnImportFileIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ImportFileTabID", DbType:="Int")>  _
	Public Property ImportFileTabID() As System.Nullable(Of Integer)
		Get
			Return Me._ImportFileTabID
		End Get
		Set
			If (Me._ImportFileTabID.Equals(value) = false) Then
				If Me._ImportFileTab.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnImportFileTabIDChanging(value)
				Me.SendPropertyChanging
				Me._ImportFileTabID = value
				Me.SendPropertyChanged("ImportFileTabID")
				Me.OnImportFileTabIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ColumnName", DbType:="VarChar(50)")>  _
	Public Property ColumnName() As String
		Get
			Return Me._ColumnName
		End Get
		Set
			If (String.Equals(Me._ColumnName, value) = false) Then
				Me.OnColumnNameChanging(value)
				Me.SendPropertyChanging
				Me._ColumnName = value
				Me.SendPropertyChanged("ColumnName")
				Me.OnColumnNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ColumnIndex", DbType:="Int")>  _
	Public Property ColumnIndex() As System.Nullable(Of Integer)
		Get
			Return Me._ColumnIndex
		End Get
		Set
			If (Me._ColumnIndex.Equals(value) = false) Then
				Me.OnColumnIndexChanging(value)
				Me.SendPropertyChanging
				Me._ColumnIndex = value
				Me.SendPropertyChanged("ColumnIndex")
				Me.OnColumnIndexChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsKeyColumn", DbType:="Bit")>  _
	Public Property IsKeyColumn() As System.Nullable(Of Boolean)
		Get
			Return Me._IsKeyColumn
		End Get
		Set
			If (Me._IsKeyColumn.Equals(value) = false) Then
				Me.OnIsKeyColumnChanging(value)
				Me.SendPropertyChanging
				Me._IsKeyColumn = value
				Me.SendPropertyChanged("IsKeyColumn")
				Me.OnIsKeyColumnChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="ImportFileTab_ImportFileColumn", Storage:="_ImportFileTab", ThisKey:="ImportFileTabID", OtherKey:="ImportFileTabID", IsForeignKey:=true)>  _
	Public Property ImportFileTab() As ImportFileTab
		Get
			Return Me._ImportFileTab.Entity
		End Get
		Set
			Dim previousValue As ImportFileTab = Me._ImportFileTab.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._ImportFileTab.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._ImportFileTab.Entity = Nothing
					previousValue.ImportFileColumns.Remove(Me)
				End If
				Me._ImportFileTab.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.ImportFileColumns.Add(Me)
					Me._ImportFileTabID = value.ImportFileTabID
				Else
					Me._ImportFileTabID = CType(Nothing, Nullable(Of Integer))
				End If
				Me.SendPropertyChanged("ImportFileTab")
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.ImportFileTab")>  _
Partial Public Class ImportFileTab
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ImportFileTabID As Integer
	
	Private _ImportFileID As System.Nullable(Of System.Guid)
	
	Private _TabName As String
	
	Private _TabXML As String
	
	Private _TabSortOrder As System.Nullable(Of Integer)
	
	Private _ImportFileDatas As EntitySet(Of ImportFileData)
	
	Private _ImportFileColumns As EntitySet(Of ImportFileColumn)
	
	Private _ImportFile As EntityRef(Of ImportFile)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnImportFileTabIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnImportFileTabIDChanged()
    End Sub
    Partial Private Sub OnImportFileIDChanging(value As System.Nullable(Of System.Guid))
    End Sub
    Partial Private Sub OnImportFileIDChanged()
    End Sub
    Partial Private Sub OnTabNameChanging(value As String)
    End Sub
    Partial Private Sub OnTabNameChanged()
    End Sub
    Partial Private Sub OnTabXMLChanging(value As String)
    End Sub
    Partial Private Sub OnTabXMLChanged()
    End Sub
    Partial Private Sub OnTabSortOrderChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnTabSortOrderChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._ImportFileDatas = New EntitySet(Of ImportFileData)(AddressOf Me.attach_ImportFileDatas, AddressOf Me.detach_ImportFileDatas)
		Me._ImportFileColumns = New EntitySet(Of ImportFileColumn)(AddressOf Me.attach_ImportFileColumns, AddressOf Me.detach_ImportFileColumns)
		Me._ImportFile = CType(Nothing, EntityRef(Of ImportFile))
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ImportFileTabID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property ImportFileTabID() As Integer
		Get
			Return Me._ImportFileTabID
		End Get
		Set
			If ((Me._ImportFileTabID = value)  _
						= false) Then
				Me.OnImportFileTabIDChanging(value)
				Me.SendPropertyChanging
				Me._ImportFileTabID = value
				Me.SendPropertyChanged("ImportFileTabID")
				Me.OnImportFileTabIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ImportFileID", DbType:="UniqueIdentifier")>  _
	Public Property ImportFileID() As System.Nullable(Of System.Guid)
		Get
			Return Me._ImportFileID
		End Get
		Set
			If (Me._ImportFileID.Equals(value) = false) Then
				If Me._ImportFile.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnImportFileIDChanging(value)
				Me.SendPropertyChanging
				Me._ImportFileID = value
				Me.SendPropertyChanged("ImportFileID")
				Me.OnImportFileIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TabName", DbType:="VarChar(50)")>  _
	Public Property TabName() As String
		Get
			Return Me._TabName
		End Get
		Set
			If (String.Equals(Me._TabName, value) = false) Then
				Me.OnTabNameChanging(value)
				Me.SendPropertyChanging
				Me._TabName = value
				Me.SendPropertyChanged("TabName")
				Me.OnTabNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TabXML", DbType:="VarChar(MAX)")>  _
	Public Property TabXML() As String
		Get
			Return Me._TabXML
		End Get
		Set
			If (String.Equals(Me._TabXML, value) = false) Then
				Me.OnTabXMLChanging(value)
				Me.SendPropertyChanging
				Me._TabXML = value
				Me.SendPropertyChanged("TabXML")
				Me.OnTabXMLChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TabSortOrder", DbType:="Int")>  _
	Public Property TabSortOrder() As System.Nullable(Of Integer)
		Get
			Return Me._TabSortOrder
		End Get
		Set
			If (Me._TabSortOrder.Equals(value) = false) Then
				Me.OnTabSortOrderChanging(value)
				Me.SendPropertyChanging
				Me._TabSortOrder = value
				Me.SendPropertyChanged("TabSortOrder")
				Me.OnTabSortOrderChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="ImportFileTab_ImportFileData", Storage:="_ImportFileDatas", ThisKey:="ImportFileTabID", OtherKey:="ImportFileTabID")>  _
	Public Property ImportFileDatas() As EntitySet(Of ImportFileData)
		Get
			Return Me._ImportFileDatas
		End Get
		Set
			Me._ImportFileDatas.Assign(value)
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="ImportFileTab_ImportFileColumn", Storage:="_ImportFileColumns", ThisKey:="ImportFileTabID", OtherKey:="ImportFileTabID")>  _
	Public Property ImportFileColumns() As EntitySet(Of ImportFileColumn)
		Get
			Return Me._ImportFileColumns
		End Get
		Set
			Me._ImportFileColumns.Assign(value)
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="ImportFile_ImportFileTab", Storage:="_ImportFile", ThisKey:="ImportFileID", OtherKey:="ImportFileID", IsForeignKey:=true)>  _
	Public Property ImportFile() As ImportFile
		Get
			Return Me._ImportFile.Entity
		End Get
		Set
			Dim previousValue As ImportFile = Me._ImportFile.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._ImportFile.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._ImportFile.Entity = Nothing
					previousValue.ImportFileTabs.Remove(Me)
				End If
				Me._ImportFile.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.ImportFileTabs.Add(Me)
					Me._ImportFileID = value.ImportFileID
				Else
					Me._ImportFileID = CType(Nothing, Nullable(Of System.Guid))
				End If
				Me.SendPropertyChanged("ImportFile")
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_ImportFileDatas(ByVal entity As ImportFileData)
		Me.SendPropertyChanging
		entity.ImportFileTab = Me
	End Sub
	
	Private Sub detach_ImportFileDatas(ByVal entity As ImportFileData)
		Me.SendPropertyChanging
		entity.ImportFileTab = Nothing
	End Sub
	
	Private Sub attach_ImportFileColumns(ByVal entity As ImportFileColumn)
		Me.SendPropertyChanging
		entity.ImportFileTab = Me
	End Sub
	
	Private Sub detach_ImportFileColumns(ByVal entity As ImportFileColumn)
		Me.SendPropertyChanging
		entity.ImportFileTab = Nothing
	End Sub
End Class
